

# Pretrain
# train
bash run_train.sh --config config/pretrain_hubert_aishell2_data_aug.yaml --GPU 0,1 --port 22123
# eval
python eval_whole_hubert_embed.py config/pretrain_hubert_aishell2_data_aug.yaml exp/md_hubert_aishell2_data_aug/kwatt_asr_25.pt resource/uych_release/datalist_uych_release_test_emb.jsonl exp/md_hubert_aishell2_data_aug/result_ep25 uych_release
python eval_whole_hubert_embed.py config/pretrain_hubert_aishell2_data_aug.yaml exp/md_hubert_aishell2_data_aug/kwatt_asr_25.pt resource/uych_3anno/datalist_uych_anno20_test_emb.jsonl exp/md_hubert_aishell2_data_aug/result_ep25 uych_anno20
python eval_whole_hubert_embed.py config/pretrain_hubert_aishell2_data_aug.yaml exp/md_hubert_aishell2_data_aug/kwatt_asr_25.pt resource/uych_3anno/datalist_uych_anno21_test_emb.jsonl exp/md_hubert_aishell2_data_aug/result_ep25 uych_anno21
python eval_whole_hubert_embed.py config/pretrain_hubert_aishell2_data_aug.yaml exp/md_hubert_aishell2_data_aug/kwatt_asr_25.pt resource/uych_3anno/datalist_uych_anno30_test_emb.jsonl exp/md_hubert_aishell2_data_aug/result_ep25 uych_anno30


# Fine-tune

# Target Norm

# fold1
# train
mkdir -p exp/md_hubert_aishell2_ft_uych_release_train_fold1_sph_md_aug; cp exp/md_hubert_aishell2_data_aug/kwatt_asr_24.pt exp/md_hubert_aishell2_ft_uych_release_train_fold1_sph_md_aug/
bash run_train.sh --config config/pretrain_hubert_aishell2_ft_uych_release_fold1_sph_md_aug.yaml --GPU 0,1 --port 22123
# eval
python eval_whole_hubert_embed.py config/pretrain_hubert_aishell2_ft_uych_release_fold1_sph_md_aug.yaml exp/md_hubert_aishell2_ft_uych_release_train_fold1_sph_md_aug/kwatt_asr_avg_40-50.pt uych_release_test_emb_cv10/val_fold1.jsonl exp/md_hubert_aishell2_ft_uych_release_train_fold1_sph_md_aug/result_avg40-50 uych_release
python eval_whole_hubert_embed.py config/pretrain_hubert_aishell2_ft_uych_release_fold1_sph_md_aug.yaml exp/md_hubert_aishell2_ft_uych_release_train_fold1_sph_md_aug/kwatt_asr_avg_40-50.pt uych_anno20_test_emb_cv10/val_fold1.jsonl exp/md_hubert_aishell2_ft_uych_release_train_fold1_sph_md_aug/result_avg40-50 uych_anno20
python eval_whole_hubert_embed.py config/pretrain_hubert_aishell2_ft_uych_release_fold1_sph_md_aug.yaml exp/md_hubert_aishell2_ft_uych_release_train_fold1_sph_md_aug/kwatt_asr_avg_40-50.pt uych_anno21_test_emb_cv10/val_fold1.jsonl exp/md_hubert_aishell2_ft_uych_release_train_fold1_sph_md_aug/result_avg40-50 uych_anno21
python eval_whole_hubert_embed.py config/pretrain_hubert_aishell2_ft_uych_release_fold1_sph_md_aug.yaml exp/md_hubert_aishell2_ft_uych_release_train_fold1_sph_md_aug/kwatt_asr_avg_40-50.pt uych_anno30_test_emb_cv10/val_fold1.jsonl exp/md_hubert_aishell2_ft_uych_release_train_fold1_sph_md_aug/result_avg40-50 uych_anno30

# Perception Norm

# fold1
# collective
# train
mkdir -p exp/md_hubert_aishell2_ft_uych_release_train_fold1_md; cp exp/md_hubert_aishell2_data_aug/kwatt_asr_24.pt exp/md_hubert_aishell2_ft_uych_release_train_fold1_md/
bash run_train.sh --config config/pretrain_hubert_aishell2_ft_uych_release_fold1_md.yaml --GPU 0,1 --port 22123
# eval
python eval_whole_hubert_embed.py config/pretrain_hubert_aishell2_ft_uych_release_fold1_md.yaml exp/md_hubert_aishell2_ft_uych_release_train_fold1_md/kwatt_asr_avg_40-50.pt uych_release_test_emb_cv10/val_fold1.jsonl exp/md_hubert_aishell2_ft_uych_release_train_fold1_md/result_avg40-50 uych_release
python eval_whole_hubert_embed.py config/pretrain_hubert_aishell2_ft_uych_release_fold1_md.yaml exp/md_hubert_aishell2_ft_uych_release_train_fold1_md/kwatt_asr_avg_40-50.pt uych_anno20_test_emb_cv10/val_fold1.jsonl exp/md_hubert_aishell2_ft_uych_release_train_fold1_md/result_avg40-50 uych_anno20
python eval_whole_hubert_embed.py config/pretrain_hubert_aishell2_ft_uych_release_fold1_md.yaml exp/md_hubert_aishell2_ft_uych_release_train_fold1_md/kwatt_asr_avg_40-50.pt uych_anno21_test_emb_cv10/val_fold1.jsonl exp/md_hubert_aishell2_ft_uych_release_train_fold1_md/result_avg40-50 uych_anno21
python eval_whole_hubert_embed.py config/pretrain_hubert_aishell2_ft_uych_release_fold1_md.yaml exp/md_hubert_aishell2_ft_uych_release_train_fold1_md/kwatt_asr_avg_40-50.pt uych_anno30_test_emb_cv10/val_fold1.jsonl exp/md_hubert_aishell2_ft_uych_release_train_fold1_md/result_avg40-50 uych_anno30

# anno1
#train
mkdir -p exp/md_hubert_aishell2_ft_uych_anno20_train_fold1_md; cp exp/md_hubert_aishell2_data_aug/kwatt_asr_24.pt exp/md_hubert_aishell2_ft_uych_anno20_train_fold1_md/
bash run_train.sh --config config/pretrain_hubert_aishell2_ft_uych_anno20_fold1_md.yaml --GPU 0,1 --port 22123
# eval
python eval_whole_hubert_embed.py config/pretrain_hubert_aishell2_ft_uych_anno20_fold1_md.yaml exp/md_hubert_aishell2_ft_uych_anno20_train_fold1_md/kwatt_asr_avg_40-50.pt uych_anno20_test_emb_cv10/val_fold1.jsonl exp/md_hubert_aishell2_ft_uych_anno20_train_fold1_md/result_avg40-50/ uych_anno20
python eval_whole_hubert_embed.py config/pretrain_hubert_aishell2_ft_uych_anno20_fold1_md.yaml exp/md_hubert_aishell2_ft_uych_anno20_train_fold1_md/kwatt_asr_avg_40-50.pt uych_anno21_test_emb_cv10/val_fold1.jsonl exp/md_hubert_aishell2_ft_uych_anno20_train_fold1_md/result_avg40-50/ uych_anno21
python eval_whole_hubert_embed.py config/pretrain_hubert_aishell2_ft_uych_anno20_fold1_md.yaml exp/md_hubert_aishell2_ft_uych_anno20_train_fold1_md/kwatt_asr_avg_40-50.pt uych_anno30_test_emb_cv10/val_fold1.jsonl exp/md_hubert_aishell2_ft_uych_anno20_train_fold1_md/result_avg40-50/ uych_anno30

# anno2
#train
mkdir -p exp/md_hubert_aishell2_ft_uych_anno21_train_fold1_md; cp exp/md_hubert_aishell2_data_aug/kwatt_asr_24.pt exp/md_hubert_aishell2_ft_uych_anno21_train_fold1_md/
bash run_train.sh --config config/pretrain_hubert_aishell2_ft_uych_anno21_fold1_md.yaml --GPU 0,1 --port 22123
# eval
python eval_whole_hubert_embed.py config/pretrain_hubert_aishell2_ft_uych_anno21_fold1_md.yaml exp/md_hubert_aishell2_ft_uych_anno21_train_fold1_md/kwatt_asr_avg_40-50.pt uych_anno20_test_emb_cv10/val_fold1.jsonl exp/md_hubert_aishell2_ft_uych_anno21_train_fold1_md/result_avg40-50/ uych_anno20
python eval_whole_hubert_embed.py config/pretrain_hubert_aishell2_ft_uych_anno21_fold1_md.yaml exp/md_hubert_aishell2_ft_uych_anno21_train_fold1_md/kwatt_asr_avg_40-50.pt uych_anno21_test_emb_cv10/val_fold1.jsonl exp/md_hubert_aishell2_ft_uych_anno21_train_fold1_md/result_avg40-50/ uych_anno21
python eval_whole_hubert_embed.py config/pretrain_hubert_aishell2_ft_uych_anno21_fold1_md.yaml exp/md_hubert_aishell2_ft_uych_anno21_train_fold1_md/kwatt_asr_avg_40-50.pt uych_anno30_test_emb_cv10/val_fold1.jsonl exp/md_hubert_aishell2_ft_uych_anno21_train_fold1_md/result_avg40-50/ uych_anno30

# anno3
#train
mkdir -p exp/md_hubert_aishell2_ft_uych_anno30_train_fold1_md; cp exp/md_hubert_aishell2_data_aug/kwatt_asr_24.pt exp/md_hubert_aishell2_ft_uych_anno30_train_fold1_md/
bash run_train.sh --config config/pretrain_hubert_aishell2_ft_uych_anno30_fold1_md.yaml --GPU 0,1 --port 22123
# eval
python eval_whole_hubert_embed.py config/pretrain_hubert_aishell2_ft_uych_anno30_fold1_md.yaml exp/md_hubert_aishell2_ft_uych_anno30_train_fold1_md/kwatt_asr_avg_40-50.pt uych_anno20_test_emb_cv10/val_fold1.jsonl exp/md_hubert_aishell2_ft_uych_anno30_train_fold1_md/result_avg40-50/ uych_anno20
python eval_whole_hubert_embed.py config/pretrain_hubert_aishell2_ft_uych_anno30_fold1_md.yaml exp/md_hubert_aishell2_ft_uych_anno30_train_fold1_md/kwatt_asr_avg_40-50.pt uych_anno21_test_emb_cv10/val_fold1.jsonl exp/md_hubert_aishell2_ft_uych_anno30_train_fold1_md/result_avg40-50/ uych_anno21
python eval_whole_hubert_embed.py config/pretrain_hubert_aishell2_ft_uych_anno30_fold1_md.yaml exp/md_hubert_aishell2_ft_uych_anno30_train_fold1_md/kwatt_asr_avg_40-50.pt uych_anno30_test_emb_cv10/val_fold1.jsonl exp/md_hubert_aishell2_ft_uych_anno30_train_fold1_md/result_avg40-50/ uych_anno30
