# model archive
model_arch: TransformerSS

# model config
model_config:
  audio_net_config:
    input_trans: &linear_common
      dim: [200, 256]
      num_block: 1
      norm: LayerNorm
      act: ReLU
    transformer_config: 
      size: 256
      self_att: MultiHeadAtt
      self_att_config: &att_common
        n_head: 4
        n_feats: 256
      cross_att: MultiHeadCrossAtt
      corss_att_config: 
        n_head: 1
        n_feats: 256
        norm: LayerNorm
      feed_forward_config: &feed_forward_common
        dim: [256, 512, 256]
        num_block: 1
        norm: LayerNorm
        act: ReLU
  vocab_net_config:
    #num_token: 31 # letter 1-26 special token ' and tow keyword pos_token 28, 29, 30 for unknown
    num_token: 73 # 0;1: blank; phone: 1,69;71 special token [71,72];73
    input_trans: 
      dim: 256
      num_block: 1
      norm: LayerNorm
      act: ReLU
    transformer_config:
      size: 256
      self_att: MultiHeadAtt
      self_att_config: *att_common
      feed_forward_config: *feed_forward_common
  predict_token: [71, 72]
  num_audio_block: 8
  num_vocab_block: 4
  loss_weight: [1, 1, 0.3]

# experimental config
exp_config:
  trained_ckpt: ""
  exp_dir: exp/ss_spectrum_fbank_rec_0
  warm_up_peak_epoch: 10
  exp_name: ss_asr
  optim_config:
    lr: 0.001
  log_config:
    level: "INFO"
    filemode: "a"
    format:  "%(asctime)s: %(message)s"
  log_interval: 5
  valid_interval: 100

# data config
data_config: &base_data_config
  epoch: 200
  start_epoch: 0
  shuffle: True
  num_worker: 8
  sph_config: !include config/base_config/self_corrupt_asr.yaml
  keyword_config:
    format: sample
    config:
      positive_prob: 1.2
      special_token: 
        sok: 71
        eok: 72
        with_trans: True

  length_key: mixspeech,speech,keyword
  #fetch_key: mixspeech,mixspeech_len,label,label_len,keyword,keyword_len,target
  fetch_key: mixspeech,mixspeech_len,speech,speech_len,label,label_len,keyword,keyword_len,target
  batch_size: 16
  data_list: /home/shiying/Work/zeus/kws/data/librispeech/datalist.train.txt
  valid_list: /home/shiying/Work/zeus/kws/data/librispeech/datalist.valid.txt
