# model archive
model_arch: EfficientNet

# model config
model_config:
  model_name: 'efficientnet-b0'
  num_classes: 470
  task: 'MT'

# experimental config
exp_config:
  finetune:
    trained_ckpt: /home/shiying/Work/zeus/kws/config/finetune/EfficientNetB0_avg.pt
    percentage_fix_layer: 90
  exp_dir: exp/MixTraningN_EfficientB0_PMT_FMT_finetune90
  exp_name: EfficientNetB0
  optim_config:
    lr: 0.001
  log_config:
    level: "INFO"
    filemode: "a"
    format:  "%(asctime)s: %(message)s"
  log_interval: 5
  valid_interval: 100

# data config
data_config: &base_data_config
  epoch: 100
  start_epoch: 0
  shuffle: True
  sph_config: !include config/base_config/self_corrupt_with_aug.yaml
  num_worker: 15
  keyword_config:
    format: fix
  fetch_key: mixspeech,speech,word_keyword,ratios
  #fetch_key: mixspeech,word_keyword
  batch_size: 512
  data_list: /home/shiying/Work/zeus/kws/data/finetune/data.list
  valid_list: /home/shiying/Work/zeus/kws/data/finetune/valid.list

test_data_config:
  <<: *base_data_config
  fetch_key: key,sph,word_keyword
  acc_data_list: data/GSC/test/clean.datalist
  ckpt: exp/CNNGSC/CNNGSC_100.pt
  batch_size: 40
  result_key: det_result, sample
  result_path: ""
