# model archive
model_arch: TransformerKWSPhone_hubert_wenet

# model config
model_config:
  audio_net_config:
    input_trans: &linear_common
      dim: [256, 256]
      num_block: 1
      norm: LayerNorm
      act: ReLU
    transformer_config: 
      size: 256
      self_att: MultiHeadAtt
      self_att_config: &att_common
        n_head: 4
        n_feats: 256
      cross_att: MultiHeadCrossAtt
      corss_att_config: 
        n_head: 1
        n_feats: 256
        norm: LayerNorm
      feed_forward_config: &feed_forward_common
        dim: [256, 512, 256]
        num_block: 1
        norm: LayerNorm
        act: ReLU
      conv_config:
        channels: 256

  kw_net_config:
    num_phn_token: 218 # phone 1-70; blank 0; sos/eos 71/72
    input_trans: 
      dim: 256
      num_block: 1
      norm: LayerNorm
      act: ReLU
    transformer_config:
      size: 256
      self_att: MultiHeadAtt
      self_att_config: *att_common
      feed_forward_config: *feed_forward_common
  num_audio_block: 6
  num_kw_block: 4
  sok: 1
  eok: 2
  loss_weight: [0.0, 1.0, 0.0]

# experimental config
exp_config:
  trained_ckpt: ""
  exp_dir: exp/md_hubert_aishell2_ft_uych_anno20_train_fold6_sph_md_aug_only_phone_encoder_only_bce
  warm_up_peak_epoch: 10
  exp_name: kwatt_asr
  optim_config:
    lr: 0.0001
  log_config:
    level: "INFO"
    filemode: "a"
    format:  "%(asctime)s: %(message)s"
  log_interval: 5
  valid_interval: 100

# data config
data_config: &base_data_config
  #epoch: 101
  epoch: 51
  start_epoch: 25
  #start_epoch: 11
  #start_epoch: 0
  shuffle: True
  num_worker: 4
  #num_worker: 16
  #num_worker: 24
  #num_worker: 30
  sph_config: !include config/base_config/self_corrupt_none_target_corrupt.yaml
  #sph_config: !include config/base_config/no_corrupt.yaml
  keyword_config:
    format: sample
    config:
      positive_prob: 1.0
      special_token:
        sok: 1
        eok: 2
        unk: 5276
        #psok: 71
        #peok: 72
        #punk: 73
        with_trans: True
      phonetic_auxiliary: phonetic_auxiliary.json
      phone_data_aug: intra_class_vow_con
  length_key: mixspeech,speech,keyword
  fetch_key: mixspeech,mixspeech_len,phn_label,phn_label_len,keyword,keyword_len,md_label,md_label_len,target
  #batch_size: 2
  batch_size: 32
  #batch_size: 128
  #data_list: /work106/weiyang/project/maolidan_thesis/experiment/text_enroll_md/resource/500h_with_wenet_drama_sinvxx_1-3s/version_kaldi_ipa/forced_alignment_cut/data_process/datalist_aishell2_clean_sort2_split8_cut_gt400.valid.txt
  data_list: uych_anno20_sph_cv10/train_fold6.jsonl
  #data_list: resource/500h_with_wenet_drama_sinvxx_1-3s/version_kaldi_ipa/forced_alignment_cut/data_process/datalist_aishell2_clean_sort2_split8_cut_gt400.train.samp10k.txt
  #data_list: /work104/weiyang/project/maolidan_thesis/experiment/text_enroll_md/resource/500h_with_wenet_drama_sinvxx_1-3s/version_kaldi_ipa/forced_alignment_cut/data_process/datalist_aishell2_clean_sort2_split8_cut_gt400.valid.txt
  valid_list: uych_anno20_sph_cv10/val_fold6.jsonl

