conv_channles: [32, 64, 128, 64, 128, 256, 512]
conv_kernels: 3
conv_strides: [[2,1], [2,1], [1,1],[1,1],[1,1],[1,1],[1,1]]
conv_module:
  #norm: 'LayerNormNonePara'
  norm: 'LayerNorm'
  #norm: 'BatchNorm2d'
  act: 'ReLU'
  norm_before: True
